function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 15-Apr-2013 02:30:30

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'MarkerSize',10,'LineWidth',3,...
    'Color',[0 0 0]);
set(plot1(1),'Marker','*','DisplayName','SPIHT');
set(plot1(2),'Marker','+','LineStyle','--','DisplayName','modified  SPIHT');
set(plot1(3),'Marker','^','DisplayName','SPECK');
set(plot1(4),'Marker','pentagram','LineStyle','--',...
    'DisplayName','modified SPECK');

% Create xlabel
xlabel('BPP','FontWeight','bold','FontSize',16);

% Create ylabel
ylabel('PSNR','FontWeight','bold','FontSize',16);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.638929559134538 0.167897327707453 0.231088335773548 0.356247069854665]);

