function createfigure2(cdata1)
%CREATEFIGURE2(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 22-Apr-2013 20:17:37

% Create figure

colormap('gray');

% Create axes
axes1 = axes('YDir','reverse','TickDir','out',...
    'Position',[0.142039106145251 0.110569105691057 0.715083798882682 0.832520325203252],...
    'Layer','top',...
    'FontSize',16,...
    'DataAspectRatio',[1 1 1],...
    'CLim',[0 255]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0.5 512.5]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0.5 512.5]);
box(axes1,'on');
hold(axes1,'all');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

