function createfigure4(X1, Y1)
%CREATEFIGURE4(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Apr-2013 15:32:51

% Create figure
figure(1);

% Create axes
axes1 = axes('Parent',figure(1),'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerSize',10,'Marker','+','LineWidth',3,'Color',[0 1 0]);

% Create xlabel
xlabel({'BPP'},'FontWeight','bold','FontSize',14);

