function createfigure3(X1, Y1)
%CREATEFIGURE3(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Apr-2013 15:29:39

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',14);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'MarkerSize',10,'Marker','*','LineWidth',3,'Color',[1 0 0]);

% Create xlabel
xlabel({'BPP'},'FontWeight','bold','FontSize',14);
hold on;
